---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-026dea5602e368e96"
  module_defaults:
    group/aws:
      region: "us-east-1"
  tasks:
    - name: Provision Ec2 instance
      ec2:
        key_name: m1files
        group: ig-postgres-tag-m5
        instance_type: t3.micro
        image: "{{ ami_id }}"
        instance_tags:
          Name: M5-ig-public-instance
          Module: 5
        wait: true
        exact_count: 1
        count_tag: M5-ig-public-instance
        vpc_subnet_id: "{{ publicSubnet1.subnet.id }}"
        assign_public_ip: yes
      register: ec2Instance
    - name: debug
      debug: var=ec2Instance
    - name: Allocate elastic IP to ec2Instance
      ec2_eip:
        in_vpc: true
        device_id: "{{ item.id }}"
        state: present
      with_items: "{{ ec2Instance.tagged_instances }}"
      register: ec2InstanceEip
        - debug: var=ec2InstanceEip
